import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: CHROME, headless: "new", args: ["--no-sandbox"] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 });
await page.goto("http://localhost:3000/", { waitUntil: "networkidle0" });
await sleep(2000);
await page.screenshot({ path: "/tmp/brand_hero.png" });
await page.screenshot({ path: "/tmp/brand_nav.png", clip: { x: 0, y: 0, width: 1440, height: 84 } });
await browser.close();
console.log("done");
